name: Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    check:
        name: Check formatting with Prettier
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v2
              env:
                  HUSKY: 0

            - run: bun install --frozen-lockfile

            - uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --check .
                  dry: true
                  only_changed: true
